### ISSUE TITLE
Input out Put

### ISSUE THREAD

**Issue by gandhiShepard** [tutsplus/node-js-from-scratch#1]
Andrew,
I am very interested to know more about how you are using Input/Output (and other utilities) for building tools to use in your daily dev workflow. what are these tools, how to you use them. this is would be a rad mini course as well. 

Thanks for this resource!
Stay awesome!

**Comment by adamarthurryan** [comment]
Hi @gandhiShepard - I'll make sure Andrew gets your comments! You can also reach him at the twitter account posted here: https://tutsplus.com/authors/andrew-burgess
